export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";
export const UPDATE_SALE_COUNT = "UPDATE_SALE_COUNT";
export const UPDATE_DAMAGE_COUNT = "UPDATE_DAMAGE_COUNT";
export const UPDATE_APPROVE_COUNT = "UPDATE_APPROVE_COUNT";
export const UPDATE_REJECT_COUNT = "UPDATE_REJECT_COUNT";
